### PR TITLE
bootstrapping qt gui project

### PR DESCRIPTION
**Pull request by guruprerana**
Added Qt Widget application configurations to the whole project. From here, we can continue adding new screens and windows under the gui folder while others add to the other teams add to the other respective folders.

### CODE REVIEW

**Review by vishrutmalik — APPROVED** [review]

**Comment by ngkan** [comment]
LGTM

**Review by ngkan — APPROVED** [review]

**Comment by ngthanhvinh** [comment]
I think it would be better if we have some scripts to build automatically for people who do not use QtCreator. I have already done it. If you agree, I will push the code to this branch.

**Comment by guruprerana** [comment]
> I think it would be better if we have some scripts to build automatically for people who do not use QtCreator. I have already done it. If you agree, I will push the code to this branch.

I think that is a good idea. Go for it!

**Comment by smover** [comment]
@ngthanhvinh   Please stick to a single build system to compile your project (it's for your sanity ;-) )

You can use the build script from Qt creator from command line (you all have the `qmake` command line tool installed). For example you can create a build folder and then call:

```
qmake <path to the .pro file>
make
``` 

This will build your project (once you called qmake once, then you just need to call make to build your poject again).

In this way you will have to maintain only one build system. Let me know if you have any question.

**Comment by ngthanhvinh** [comment]
@smover I did not change the build system. The scripts only create the build folder and run automatically.

**Pull request merged**
