### PR TITLE
GUI Skeleton

### PR DESCRIPTION
**Pull request by guruprerana**
Added skeleton of the gui with navigation bar and signals for navigation. Also added the different pages that we will need.

### CODE REVIEW

**Comment by ngkan** [comment]
Maxime and I have agreed that "portfolio" is a more precise term than "user", so maybe we should change "user" to "portfolio" in the future.

Nonetheless, 
LGTM

**Review by ngkan — DISMISSED** [review]

**Comment by guruprerana** [comment]
> Maxime and I have agreed that "portfolio" is a more precise term than "user", so maybe we should change "user" to "portfolio" in the future.
> 
> Nonetheless,
> LGTM

Thanks for that! I shall make the change to portfolio right away.

**Comment by ngthanhvinh** [comment]
I personally do not like resizable window, could we make it fullscreen and unresizable?

**Comment by guruprerana** [comment]
> I personally do not like resizable window, could we make it fullscreen and unresizable?

@ngthanhvinh Thanks for the comment! Potentially, I think we could make both versions work. In terms of a UI perspective, I am not sure every user would like an only full screen application. But we can definitely look at implementing an additional full screen version where we can display more data in one screen utilizing the additional real estate. What do you think?

**Pull request merged**
